from __future__ import annotations

from dataclasses import dataclass, field

from app.integrations.models import (
    ConnectorAuthType,
    ConnectorCategory,
    ConnectorKind,
    ConnectorType,
)


@dataclass(frozen=True, slots=True)
class CatalogSpec:
    """Static metadata for one catalog entry. Live status is computed
    separately at request time — see build_catalog() in phase9.py."""

    id: str
    name: str
    description: str
    category: ConnectorCategory
    connector_type: ConnectorType
    icon: str
    auth_type: ConnectorAuthType
    capabilities: list[str] = field(default_factory=list)
    #: Canonical capability ids (see app/integrations/capabilities.py). These
    #: are what the agent layer routes on and what risk/approval is derived
    #: from; `capabilities` above is display text only. Declaring one here is
    #: a statement about what connecting this account would authorise — NOT a
    #: claim that it is implemented; `implemented` remains the only source of
    #: truth for that.
    canonical_capabilities: list[str] = field(default_factory=list)
    popular: bool = False
    documentation_url: str | None = None
    implemented: bool = False
    requires: list[str] = field(default_factory=list)
    #: Whether this is a service a user connects their own account to, or a
    #: piece of THYNACT's own running infrastructure. See ConnectorKind.
    kind: ConnectorKind = ConnectorKind.USER_CONNECTOR


# Entries marked `implemented=True` have a real adapter and focused tests.
# Credentials and an explicit connection test are still required before a
# connector is shown as live; catalog metadata alone never implies that.
CATALOG: list[CatalogSpec] = [
    # --- Automation ---
    CatalogSpec(
        id="n8n",
        name="n8n",
        description="Trigger self-hosted or cloud n8n workflows over webhooks.",
        category=ConnectorCategory.AUTOMATION,
        connector_type=ConnectorType.WEBHOOK,
        icon="Zap",
        auth_type=ConnectorAuthType.WEBHOOK_SECRET,
        capabilities=["Trigger workflow", "Pass payload", "Read execution result"],
        canonical_capabilities=[
            "automation.workflow.trigger",
            "automation.run.read",
        ],
        popular=True,
        documentation_url="https://n8n.io",
        implemented=True,
        requires=["N8N_BASE_URL"],
    ),
    CatalogSpec(
        id="zapier",
        name="Zapier",
        description="Trigger one configured Zapier webhook from a governed workflow.",
        category=ConnectorCategory.AUTOMATION,
        connector_type=ConnectorType.WEBHOOK,
        icon="Workflow",
        auth_type=ConnectorAuthType.WEBHOOK_SECRET,
        capabilities=["Trigger zap", "Pass payload"],
        canonical_capabilities=[
            "automation.workflow.trigger",
        ],
        documentation_url="https://zapier.com",
        implemented=True,
        requires=["ZAPIER_WEBHOOK_URL"],
    ),
    CatalogSpec(
        id="make",
        name="Make",
        description="Trigger Make (formerly Integromat) scenarios.",
        category=ConnectorCategory.AUTOMATION,
        connector_type=ConnectorType.WEBHOOK,
        icon="GitMerge",
        auth_type=ConnectorAuthType.WEBHOOK_SECRET,
        capabilities=["Trigger scenario", "Pass payload"],
        canonical_capabilities=[
            "automation.workflow.trigger",
        ],
        documentation_url="https://www.make.com",
        implemented=True,
        requires=["MAKE_WEBHOOK_URL"],
    ),
    # --- AI ---
    CatalogSpec(
        id="openai",
        name="OpenAI",
        description="Use GPT models as an alternate LLM provider.",
        category=ConnectorCategory.AI,
        connector_type=ConnectorType.API,
        icon="Bot",
        auth_type=ConnectorAuthType.API_KEY,
        capabilities=["Verify API key", "List models"],
        canonical_capabilities=[
            "ai.model.list",
            "ai.completion.create",
        ],
        popular=True,
        documentation_url="https://openai.com",
        implemented=True,
        requires=["OPENAI_API_KEY"],
    ),
    CatalogSpec(
        id="anthropic",
        name="Anthropic",
        description="Use Claude models as an alternate LLM provider.",
        category=ConnectorCategory.AI,
        connector_type=ConnectorType.API,
        icon="Sparkles",
        auth_type=ConnectorAuthType.API_KEY,
        capabilities=["Verify API key", "List models"],
        canonical_capabilities=[
            "ai.model.list",
            "ai.completion.create",
        ],
        popular=True,
        documentation_url="https://www.anthropic.com",
        implemented=True,
        requires=["ANTHROPIC_API_KEY"],
    ),
    CatalogSpec(
        id="gemini",
        name="Google Gemini",
        description="THYNACT's built-in LLM provider option for orchestration and autonomous runs.",
        category=ConnectorCategory.AI,
        connector_type=ConnectorType.API,
        icon="Gem",
        auth_type=ConnectorAuthType.API_KEY,
        capabilities=["Chat completion", "Multi-agent reasoning"],
        canonical_capabilities=[
            "ai.model.list",
            "ai.completion.create",
        ],
        popular=True,
        documentation_url="https://ai.google.dev",
        implemented=True,
        requires=["GEMINI_API_KEY"],
    ),
    # --- Developer / infra ---
    CatalogSpec(
        id="github",
        name="GitHub",
        description="Read repos, open issues/PRs, and react to events.",
        category=ConnectorCategory.DEVELOPER,
        connector_type=ConnectorType.OAUTH,
        icon="Github",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["Connect account", "Verify identity", "Post messages"],
        canonical_capabilities=[
            "identity.account.read",
            "repo.metadata.read",
            "repo.content.read",
            "repo.issue.create",
            "repo.branch.merge",
        ],
        popular=True,
        documentation_url="https://github.com",
        implemented=True,
        requires=["GITHUB_OAUTH_CLIENT_ID", "GITHUB_OAUTH_CLIENT_SECRET"],
    ),
    CatalogSpec(
        id="gitlab",
        name="GitLab",
        description="Read repos, open issues/MRs, and react to pipeline events.",
        category=ConnectorCategory.DEVELOPER,
        connector_type=ConnectorType.OAUTH,
        icon="GitBranch",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["Connect account", "Verify identity"],
        canonical_capabilities=[
            "identity.account.read",
            "repo.metadata.read",
            "repo.content.read",
            "repo.issue.create",
            "repo.branch.merge",
        ],
        documentation_url="https://gitlab.com",
        implemented=True,
        requires=["GITLAB_OAUTH_CLIENT_ID", "GITLAB_OAUTH_CLIENT_SECRET"],
    ),
    CatalogSpec(
        id="cloudflare",
        name="Cloudflare",
        description="Manage DNS, Pages deployments, and edge config.",
        category=ConnectorCategory.DEVELOPER,
        connector_type=ConnectorType.API,
        icon="Cloud",
        auth_type=ConnectorAuthType.API_KEY,
        capabilities=["Verify API token"],
        canonical_capabilities=[
            "identity.account.read",
            "cloud.dns.read",
        ],
        documentation_url="https://www.cloudflare.com",
        implemented=True,
        requires=["CLOUDFLARE_API_TOKEN"],
    ),
    CatalogSpec(
        id="render",
        name="Render",
        description="Trigger deploys and read service status.",
        category=ConnectorCategory.DEVELOPER,
        connector_type=ConnectorType.API,
        icon="Server",
        auth_type=ConnectorAuthType.API_KEY,
        capabilities=["Verify API key"],
        canonical_capabilities=[
            "identity.account.read",
            "cloud.service.read",
            "cloud.deploy.trigger",
        ],
        documentation_url="https://render.com",
        implemented=True,
        requires=["RENDER_API_KEY"],
    ),
    CatalogSpec(
        id="vercel",
        name="Vercel",
        description="Trigger deploys and read project status.",
        category=ConnectorCategory.DEVELOPER,
        connector_type=ConnectorType.API,
        icon="Triangle",
        auth_type=ConnectorAuthType.API_KEY,
        capabilities=["Deploy trigger", "Project status"],
        canonical_capabilities=[
            "cloud.service.read",
            "cloud.deploy.trigger",
        ],
        documentation_url="https://vercel.com",
        implemented=True,
        requires=["VERCEL_API_TOKEN"],
    ),
    # --- Productivity ---
    CatalogSpec(
        id="slack",
        name="Slack",
        description="Post messages and react to events in Slack channels.",
        category=ConnectorCategory.PRODUCTIVITY,
        connector_type=ConnectorType.OAUTH,
        icon="MessageSquare",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["Connect account", "Verify identity", "List channels", "Read messages", "Post messages"],
        canonical_capabilities=[
            "identity.account.read",
            "chat.channel.list",
            "chat.message.list",
            "chat.message.send",
        ],
        popular=True,
        documentation_url="https://slack.com",
        implemented=True,
        requires=["SLACK_OAUTH_CLIENT_ID", "SLACK_OAUTH_CLIENT_SECRET"],
    ),
    CatalogSpec(
        id="discord",
        name="Discord",
        description="Post messages and react to events in Discord servers.",
        category=ConnectorCategory.PRODUCTIVITY,
        connector_type=ConnectorType.WEBHOOK,
        icon="MessagesSquare",
        auth_type=ConnectorAuthType.WEBHOOK_SECRET,
        capabilities=["Post message"],
        canonical_capabilities=[
            "identity.account.read",
            "chat.message.list",
            "chat.message.send",
        ],
        documentation_url="https://discord.com",
        implemented=True,
        requires=["DISCORD_WEBHOOK_URL"],
    ),
    CatalogSpec(
        id="telegram",
        name="Telegram",
        description="Send governed messages through a Telegram bot.",
        category=ConnectorCategory.PRODUCTIVITY,
        connector_type=ConnectorType.API,
        icon="Send",
        auth_type=ConnectorAuthType.API_KEY,
        capabilities=["Verify bot", "Send message"],
        canonical_capabilities=["identity.account.read", "chat.message.send"],
        documentation_url="https://core.telegram.org/bots/api",
        implemented=True,
        requires=["TELEGRAM_BOT_TOKEN"],
    ),
    CatalogSpec(
        id="whatsapp",
        name="WhatsApp Cloud",
        description="Verify a WhatsApp Business phone and send governed text messages.",
        category=ConnectorCategory.PRODUCTIVITY,
        connector_type=ConnectorType.API,
        icon="MessageCircle",
        auth_type=ConnectorAuthType.BEARER,
        capabilities=["Verify business phone", "Send text message"],
        canonical_capabilities=["identity.account.read", "chat.message.send"],
        documentation_url="https://developers.facebook.com/docs/whatsapp/cloud-api",
        implemented=True,
        requires=["META_ACCESS_TOKEN", "WHATSAPP_PHONE_NUMBER_ID"],
    ),
    CatalogSpec(
        id="instagram",
        name="Instagram",
        description="Verify an Instagram professional account, message users, and publish image posts.",
        category=ConnectorCategory.PRODUCTIVITY,
        connector_type=ConnectorType.API,
        icon="Instagram",
        auth_type=ConnectorAuthType.BEARER,
        capabilities=["Verify professional account", "Send text message", "Publish image post"],
        canonical_capabilities=[
            "identity.account.read",
            "chat.message.send",
            "social.post.publish",
        ],
        documentation_url="https://developers.facebook.com/docs/instagram-api",
        implemented=True,
        requires=["META_ACCESS_TOKEN", "INSTAGRAM_BUSINESS_ACCOUNT_ID"],
    ),
    CatalogSpec(
        id="notion",
        name="Notion",
        description="Read and write Notion pages and databases.",
        category=ConnectorCategory.PRODUCTIVITY,
        connector_type=ConnectorType.OAUTH,
        icon="FileText",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["Connect account", "Verify identity"],
        canonical_capabilities=[
            "identity.account.read",
            "docs.page.read",
            "docs.page.write",
        ],
        popular=True,
        documentation_url="https://www.notion.so",
        implemented=True,
        requires=["NOTION_OAUTH_CLIENT_ID", "NOTION_OAUTH_CLIENT_SECRET"],
    ),
    CatalogSpec(
        id="linear",
        name="Linear",
        description="Create and update issues in Linear.",
        category=ConnectorCategory.PRODUCTIVITY,
        connector_type=ConnectorType.API,
        icon="ListTodo",
        auth_type=ConnectorAuthType.API_KEY,
        capabilities=["Create issue", "Update issue"],
        canonical_capabilities=[
            "tracker.issue.list",
            "tracker.issue.create",
            "tracker.issue.update",
        ],
        popular=True,
        documentation_url="https://linear.app",
        implemented=True,
        requires=["LINEAR_API_KEY"],
    ),
    CatalogSpec(
        id="jira",
        name="Jira",
        description="Read Jira identity and search issues through the Cloud API.",
        category=ConnectorCategory.PRODUCTIVITY,
        connector_type=ConnectorType.OAUTH,
        icon="Bug",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["Create issue", "Update issue"],
        canonical_capabilities=[
            "tracker.issue.list",
            "tracker.issue.create",
            "tracker.issue.update",
        ],
        documentation_url="https://www.atlassian.com/software/jira",
        implemented=True,
        requires=[
            "JIRA_OAUTH_CLIENT_ID",
            "JIRA_OAUTH_CLIENT_SECRET",
            "JIRA_CLOUD_ID",
        ],
    ),
    CatalogSpec(
        id="teams",
        name="Microsoft Teams",
        description="Post messages to Microsoft Teams channels.",
        category=ConnectorCategory.PRODUCTIVITY,
        connector_type=ConnectorType.WEBHOOK,
        icon="Users",
        auth_type=ConnectorAuthType.WEBHOOK_SECRET,
        capabilities=["Post message"],
        canonical_capabilities=[
            "identity.account.read",
            "chat.message.list",
            "chat.message.send",
        ],
        implemented=True,
        requires=["TEAMS_WEBHOOK_URL"],
        documentation_url="https://www.microsoft.com/microsoft-teams",
    ),
    # --- Google ---
    CatalogSpec(
        id="gmail",
        name="Gmail",
        description="Read and send email through a Gmail account.",
        category=ConnectorCategory.GOOGLE,
        connector_type=ConnectorType.OAUTH,
        icon="Mail",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["Read email", "Send email"],
        canonical_capabilities=[
            "identity.account.read",
            "mail.message.list",
            "mail.message.read",
            "mail.draft.create",
            "mail.message.send",
        ],
        popular=True,
        documentation_url="https://mail.google.com",
        implemented=True,
        requires=["GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_SECRET"],
    ),
    CatalogSpec(
        id="google_calendar",
        name="Google Calendar",
        description="Read and create Google Calendar events.",
        category=ConnectorCategory.GOOGLE,
        connector_type=ConnectorType.OAUTH,
        icon="Calendar",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["Read events", "Create events"],
        canonical_capabilities=[
            "identity.account.read",
            "calendar.event.list",
            "calendar.event.create",
            "calendar.event.update",
            "calendar.event.delete",
        ],
        popular=True,
        documentation_url="https://calendar.google.com",
        implemented=True,
        requires=["GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_SECRET"],
    ),
    CatalogSpec(
        id="google_drive",
        name="Google Drive",
        description="Read and write files in Google Drive.",
        category=ConnectorCategory.GOOGLE,
        connector_type=ConnectorType.OAUTH,
        icon="HardDrive",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["Read files", "Write files"],
        canonical_capabilities=[
            "identity.account.read",
            "files.file.list",
            "files.file.read",
            "files.file.write",
            "files.file.delete",
        ],
        popular=True,
        documentation_url="https://drive.google.com",
        implemented=True,
        requires=["GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_SECRET"],
    ),
    # --- Data ---
    CatalogSpec(
        id="postgresql",
        name="PostgreSQL",
        description="THYNACT's own durable persistence backend for tasks, memory, workflows, and more.",
        category=ConnectorCategory.DATA,
        connector_type=ConnectorType.API,
        icon="Database",
        auth_type=ConnectorAuthType.NONE,
        capabilities=["Durable storage", "Full-text + pgvector search"],
        canonical_capabilities=[
            "data.record.read",
            "data.record.write",
            "data.search.semantic",
        ],
        popular=True,
        documentation_url="https://www.postgresql.org",
        implemented=True,
        requires=["DATABASE_URL"],
        kind=ConnectorKind.SYSTEM_INFRASTRUCTURE,
    ),
    CatalogSpec(
        id="redis",
        name="Redis",
        description="THYNACT's own durable job queue backend.",
        category=ConnectorCategory.DATA,
        connector_type=ConnectorType.API,
        icon="Layers",
        auth_type=ConnectorAuthType.NONE,
        capabilities=["Job queue"],
        canonical_capabilities=[
            "queue.job.read",
            "queue.job.enqueue",
        ],
        documentation_url="https://redis.io",
        implemented=True,
        requires=["REDIS_URL"],
        kind=ConnectorKind.SYSTEM_INFRASTRUCTURE,
    ),
    CatalogSpec(
        id="supabase",
        name="Supabase",
        description="Read records from one configured Supabase table.",
        category=ConnectorCategory.DATA,
        connector_type=ConnectorType.API,
        icon="Flame",
        auth_type=ConnectorAuthType.API_KEY,
        capabilities=["Database access", "Auth", "Storage"],
        canonical_capabilities=[
            "data.record.read",
            "data.record.write",
            "auth.user.list",
            "files.file.read",
            "files.file.write",
        ],
        documentation_url="https://supabase.com",
        implemented=True,
        requires=["SUPABASE_URL", "SUPABASE_ANON_KEY", "SUPABASE_READ_TABLE"],
    ),
    # --- Other useful ---
    CatalogSpec(
        id="dropbox",
        name="Dropbox",
        description="Read Dropbox account details and list file metadata.",
        category=ConnectorCategory.OTHER,
        connector_type=ConnectorType.OAUTH,
        icon="Box",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["Read files", "Write files"],
        canonical_capabilities=[
            "files.file.list",
            "files.file.read",
            "files.file.write",
            "files.file.delete",
        ],
        documentation_url="https://www.dropbox.com",
        implemented=True,
        requires=["DROPBOX_OAUTH_CLIENT_ID", "DROPBOX_OAUTH_CLIENT_SECRET"],
    ),
    CatalogSpec(
        id="onedrive",
        name="OneDrive",
        description="Read Microsoft account details and list OneDrive files.",
        category=ConnectorCategory.OTHER,
        connector_type=ConnectorType.OAUTH,
        icon="CloudCog",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["Read files", "Write files"],
        canonical_capabilities=[
            "files.file.list",
            "files.file.read",
            "files.file.write",
            "files.file.delete",
        ],
        documentation_url="https://onedrive.live.com",
        implemented=True,
        requires=["MICROSOFT_OAUTH_CLIENT_ID", "MICROSOFT_OAUTH_CLIENT_SECRET"],
    ),
    CatalogSpec(
        id="hubspot",
        name="HubSpot",
        description="Read HubSpot account details and list CRM contacts.",
        category=ConnectorCategory.OTHER,
        connector_type=ConnectorType.OAUTH,
        icon="Magnet",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["CRM contacts", "Deals", "Tickets"],
        canonical_capabilities=[
            "crm.contact.list",
            "crm.contact.update",
            "crm.deal.list",
            "crm.ticket.list",
        ],
        documentation_url="https://www.hubspot.com",
        implemented=True,
        requires=["HUBSPOT_OAUTH_CLIENT_ID", "HUBSPOT_OAUTH_CLIENT_SECRET"],
    ),
    CatalogSpec(
        id="salesforce",
        name="Salesforce",
        description="Read Salesforce organization details and list contacts.",
        category=ConnectorCategory.OTHER,
        connector_type=ConnectorType.OAUTH,
        icon="CloudSun",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["CRM records"],
        canonical_capabilities=[
            "crm.contact.list",
            "crm.contact.update",
            "crm.deal.list",
        ],
        documentation_url="https://www.salesforce.com",
        implemented=True,
        requires=[
            "SALESFORCE_OAUTH_CLIENT_ID",
            "SALESFORCE_OAUTH_CLIENT_SECRET",
            "SALESFORCE_INSTANCE_URL",
        ],
    ),
    CatalogSpec(
        id="stripe",
        name="Stripe",
        description="Read payments/subscriptions and react to billing events.",
        category=ConnectorCategory.OTHER,
        connector_type=ConnectorType.API,
        icon="CreditCard",
        auth_type=ConnectorAuthType.API_KEY,
        capabilities=["Payments", "Subscriptions", "Webhooks"],
        canonical_capabilities=[
            "identity.account.read",
            "commerce.payment.list",
            "commerce.subscription.list",
            "commerce.refund.create",
        ],
        documentation_url="https://stripe.com",
        implemented=True,
        requires=["STRIPE_SECRET_KEY"],
    ),
    CatalogSpec(
        id="shopify",
        name="Shopify",
        description="Read a Shopify store, products, and orders through the Admin API.",
        category=ConnectorCategory.OTHER,
        connector_type=ConnectorType.API,
        icon="ShoppingBag",
        auth_type=ConnectorAuthType.BEARER,
        capabilities=["Verify store", "List products", "List orders"],
        canonical_capabilities=[
            "identity.account.read",
            "commerce.product.list",
            "commerce.order.list",
        ],
        documentation_url="https://shopify.dev/docs/api/admin-graphql",
        implemented=True,
        requires=["SHOPIFY_ADMIN_ACCESS_TOKEN", "SHOPIFY_SHOP_DOMAIN"],
    ),
    CatalogSpec(
        id="amazon",
        name="Amazon Selling Partner API",
        description="Verify an Amazon seller account through the signed SP-API.",
        category=ConnectorCategory.OTHER,
        connector_type=ConnectorType.OAUTH,
        icon="Package",
        auth_type=ConnectorAuthType.OAUTH2,
        capabilities=["Verify seller account"],
        canonical_capabilities=["identity.account.read"],
        documentation_url="https://developer-docs.amazon.com/sp-api/docs/onboarding-overview",
        implemented=True,
        requires=[
            "AMAZON_LWA_CLIENT_ID",
            "AMAZON_LWA_CLIENT_SECRET",
            "AMAZON_LWA_REFRESH_TOKEN",
            "AMAZON_AWS_ACCESS_KEY_ID",
            "AMAZON_AWS_SECRET_ACCESS_KEY",
        ],
    ),
    CatalogSpec(
        id="snapchat",
        name="Snapchat",
        description="Verify a Snapchat Marketing API organization and ad accounts.",
        category=ConnectorCategory.OTHER,
        connector_type=ConnectorType.API,
        icon="Ghost",
        auth_type=ConnectorAuthType.BEARER,
        capabilities=["Verify marketing account"],
        canonical_capabilities=["identity.account.read"],
        documentation_url="https://developers.snap.com/marketing-api/home",
        implemented=True,
        requires=["SNAPCHAT_ACCESS_TOKEN"],
    ),
    CatalogSpec(
        id="woocommerce",
        name="WooCommerce",
        description="Read a WooCommerce store, products, and orders.",
        category=ConnectorCategory.OTHER,
        connector_type=ConnectorType.API,
        icon="ShoppingCart",
        auth_type=ConnectorAuthType.API_KEY,
        capabilities=["Verify store", "List products", "List orders"],
        canonical_capabilities=[
            "identity.account.read",
            "commerce.product.list",
            "commerce.order.list",
        ],
        documentation_url="https://woocommerce.github.io/woocommerce-rest-api-docs/",
        implemented=True,
        requires=[
            "WOOCOMMERCE_STORE_URL",
            "WOOCOMMERCE_CONSUMER_KEY",
            "WOOCOMMERCE_CONSUMER_SECRET",
        ],
    ),
]


def list_catalog() -> list[CatalogSpec]:
    return list(CATALOG)


def get_catalog_spec(connector_id: str) -> CatalogSpec | None:
    for spec in CATALOG:
        if spec.id == connector_id:
            return spec
    return None
